image: maven:latest

stages:
  - build
  - tests
  - package

build:
  stage: build
  script:
    - mvn compile

tests:
  stage: tests
  script:
    - mvn test

package:
  stage: package

  only:
    - develop
    - main

  script:
    - mvn package

  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - target/*.jar
    expire_in: 1 week