image: maven:latest

stages:
  - build
  - test
  - package

build:
  stage: build
  image: docker:latest
  script:
    - mvn clean install
    - DOCKER_BUILDKIT=1 docker compose build

test:
  stage: test
  script:
    - mvn test

package:
  stage: package

  only:
    - develop
    - main

  script:
    - mvn package

  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - target/*.jar
    expire_in: 1 week