openapi: 3.0.0

info:
  description: "This is API of the engine service of RNApdbee v3.0."
  version: "1.0.16"
  title: "RNApdbee Engine API"


tags:
  - name: "Calculations"
    description: "RNApdbee engine API which is able to perform sequential calculations"

servers:
  - url: '{protocol}://{URL}:{port}/calculation-api/v1/'
    variables:
      port:
        enum:
          - '8080'
          - '8081'
        default: '8080'
      URL:
        default: 'localhost'
      protocol:
        enum:
          - 'http'
          - 'https'
        default: 'http'

paths:
  /3d/:
    post:
      tags:
        - "Calculations"
      summary: "Perform a 3D to Dot-Bracket calculation"
      description: ""
      parameters:
        - $ref: "#/components/parameters/modelSelection"
        - $ref: "#/components/parameters/analysisTool"
        - $ref: "#/components/parameters/nonCanonicalHandling"
        - $ref: "#/components/parameters/removeIsolated"
        - $ref: "#/components/parameters/structuralElementsHandling"
        - $ref: "#/components/parameters/visualizationTool"
        - $ref: "#/components/parameters/contentDispositionHeader"
      requestBody:
        description: ""
        required: true
        content:
          text/plain:
            schema:
              type: "string"
              example: "content of the file"
      responses:
        "400":
          description: "Bad request"
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Output3D"

  /2d/:
    post:
      tags:
        - "Calculations"
      summary: "Perform a 2D to Dot-Bracket calculation"
      description: ""
      parameters:
        - $ref: "#/components/parameters/removeIsolated"
        - $ref: "#/components/parameters/structuralElementsHandling"
        - $ref: "#/components/parameters/visualizationTool"
        - $ref: "#/components/parameters/contentDispositionHeader"
      requestBody:
        description: ""
        required: true
        content:
          text/plain:
            schema:
              type: "string"
              example: "content of the file (in either dbn, ct or bpseq format)"
      responses:
        "400":
          description: "Bad request"
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Output2D"

  /multi/:
    post:
      tags:
        - "Calculations"
      summary: "Perform a 3D to multi 2D calculation"
      description: ""
      parameters:
        - $ref: "#/components/parameters/modelSelection"
        - $ref: "#/components/parameters/includeNonCanonical"
        - $ref: "#/components/parameters/removeIsolated"
        - $ref: "#/components/parameters/visualizationTool"
        - $ref: "#/components/parameters/contentDispositionHeader"
      requestBody:
        description: ""
        required: true
        content:
          text/plain:
            schema:
              type: "string"
              example: "content of the file"
      responses:
        "400":
          description: "Bad request"
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OutputMulti"

components:
  parameters:
    modelSelection:
      in: query
      name: modelSelection
      required: true
      schema:
        type: "string"
        enum: [ "FIRST", "ALL" ]
    analysisTool:
      in: query
      name: analysisTool
      required: true
      schema:
        type: "string"
        enum:
          - "FR3D_PYTHON"
          - "BPNET"
          - "BARNABA"
          - "RNAVIEW"
          - "MC_ANNOTATE"
          - "RNAPOLIS"
    nonCanonicalHandling:
      in: query
      name: nonCanonicalHandling
      required: true
      schema:
        type: "string"
        enum:
          - "VISUALIZATION_ONLY"
          - "TEXT_AND_VISUALIZATION"
          - "IGNORE"
    removeIsolated:
      in: query
      name: removeIsolated
      required: true
      schema:
        type: "boolean"
        enum: [ true, false ]
    includeNonCanonical:
      in: query
      name: includeNonCanonical
      required: true
      schema:
        type: "boolean"
        enum: [ true, false ]
    structuralElementsHandling:
      in: query
      name: structuralElementsHandling
      required: true
      schema:
        type: "string"
        enum: [ "USE_PSEUDOKNOTS", "IGNORE_PSEUDOKNOTS" ]
    visualizationTool:
      in: query
      name: visualizationTool
      required: true
      schema:
        type: "string"
        enum: [ "VARNA", "PSEUDO_VIEWER", "R_CHIE", "RNA_GLIB", "FORNA", "RNA_PUZZLER", "RNA_TURTLE", "RNA_TRAVELER", "BARNABA", "NONE" ]
    contentDispositionHeader:
      in: header
      name: Content-Disposition
      required: true
      schema:
        type: string
        description: Used only with `application/pdf` responses
        example: attachment; filename="name.pdf"

  schemas:
    Output3D:
      type: "object"
      properties:
        title:
          type: "string"
          description: "Title of the model taken from analyzed pdb/mmcif file. Not every file contains the title."
          example: "GLYCYL-TRNA(UCC)1B ANTICODON STEM-LOOP FROM STAPHYLOCOCCUS EPIDERMIDIS"
        models:
          type: "array"
          description: "Analyzed models."
          items:
            $ref: "#/components/schemas/SingleTertiaryModelOutput"
      required:
        - "output2D"
        - "models"

    SingleTertiaryModelOutput:
      type: "object"
      properties:
        modelNumber:
          type: "integer"
          example: "1"
        output2D:
          $ref: "#/components/schemas/Output2D"
        messages:
          type: "array"
          description: "Log messages written during the analysis."
          items:
            type: "string"
            example: "Multiplet identified: A.U7 -> [A.C6, A.U8]"
        canonicalInteractions:
          $ref: "#/components/schemas/TertiaryInteractions"
        nonCanonicalInteractions:
          $ref: "#/components/schemas/TertiaryInteractions"
        interStrandInteractions:
          $ref: "#/components/schemas/TertiaryInteractions"
        stackingInteractions:
          $ref: "#/components/schemas/TertiaryInteractions"
        basePhosphateInteractions:
          $ref: "#/components/schemas/TertiaryInteractions"
        baseRiboseInteractions:
          $ref: "#/components/schemas/TertiaryInteractions"

    TertiaryInteractions:
      type: "array"
      items:
        type: "object"
        properties:
          interactionType:
            type: "string"
            example: "base - base"
          saenger:
            $ref: "#/components/schemas/Saenger"
          leontisWesthof:
            $ref: "#/components/schemas/LeontisWesthof"
          bPh:
            $ref: "#/components/schemas/BPh"
          br:
            $ref: "#/components/schemas/BR"
          stackingTopology:
            $ref: "#/components/schemas/StackingTopology"
          leftResidue:
            $ref: "#/components/schemas/Residue"
          rightResidue:
            $ref: "#/components/schemas/Residue"
        required:
          - "interactionType"
          - "leftResidue"
          - "rightResidue"

    OutputMulti:
      type: "object"
      properties:
        title:
          type: "string"
          example: "GLYCYL-TRNA(UCC)1B ANTICODON STEM-LOOP FROM STAPHYLOCOCCUS EPIDERMIDIS"
        entries:
          type: "array"
          items:
            $ref: "#/components/schemas/OutputMultiEntry"
        consensualVisualization:
          $ref: "#/components/schemas/ConsensualVisualization"
      required:
        - "entries"
        - "consensualVisualization"

    OutputMultiEntry:
      type: "object"
      properties:
        output2D:
          $ref: "#/components/schemas/Output2D"
        adapterEnums:
          type: "array"
          items:
            type: "string"
            description: "adapter enums for which this entry object was created"
            example: "FR3D"
      required:
        - "output2D"
        - "adapterEnums"

    ConsensualVisualization:
      type: "object"
      properties:
        svgFile:
          type: "string"
          description: "base64-encoded SVG file"
          example: "S29jaGFtIFBvbGl0ZWNobmlrxJkgUG96bmHFhHNrxIU="

    Output2D:
      type: "object"
      properties:
        strands:
          $ref: "#/components/schemas/DotBracket"
        bpSeq:
          $ref: "#/components/schemas/BPSEQ"
        ct:
          $ref: "#/components/schemas/CT"
        interactions:
          $ref: "#/components/schemas/Interactions"
        structuralElements:
          $ref: "#/components/schemas/StructuralElements"
        imageInformation:
          $ref: "#/components/schemas/ImageInformation"
      required:
        - "bpSeq"
        - "ct"
        - "structuralElements"
        - "imageInformation"

    ImageInformation:
      type: "object"
      properties:
        svgFile:
          type: "string"
          description: "base64-encoded SVG file"
          example: "S29jaGFtIFBvbGl0ZWNobmlrxJkgUG96bmHFhHNrxIU="
        successfulVisualizationTool:
          $ref: "#/components/schemas/VisualizationTool"
        failedVisualizationTool:
          $ref: "#/components/schemas/VisualizationTool"
        drawingResult:
          $ref: "#/components/schemas/DrawingResult"

    BPSEQ:
      type: "array"
      items:
        type: "string"
        example: "1 G 0"

    CT:
      type: "array"
      items:
        type: "string"
        example: "1 G 0 2 0 1"

    Interactions:
      type: "array"
      description: "mandatory for 2D analysis result, null in 3D and consensual analysis result"
      items:
        type: "string"
        example: "A.A181 - Z.U418"

    DotBracket:
      type: "array"
      description: "mandatory for 2D and consensual analysis result, null in 3D analysis result"
      items:
        $ref: "#/components/schemas/StrandEntry"

    StrandEntry:
      type: "object"
      properties:
        name:
          type: "string"
          example: "A"
        sequence:
          type: "string"
          example: "uGUUAUUUU"
        structure:
          type: "string"
          example: ".]]]]]..."

    StructuralElements:
      type: "object"
      properties:
        stems:
          $ref: "#/components/schemas/StructuralElementsArray"
        loops:
          $ref: "#/components/schemas/StructuralElementsArray"
        singleStrands:
          $ref: "#/components/schemas/StructuralElementsArray"
        singleStrands5p:
          $ref: "#/components/schemas/StructuralElementsArray"
        singleStrands3p:
          $ref: "#/components/schemas/StructuralElementsArray"
        coordinates:
          type: "string"
          description: "Generated pdb file. Not relevand (null) for 2D analysis"
          example: "ATOM     33  P     G A   2      17.038   9.250   4.315  1.00  1.00           P"
      required:
        - "stems"
        - "loops"
        - "singleStrands"
        - "singleStrands5p"
        - "singleStrands3p"

    StructuralElementsArray:
      type: "array"
      items:
        type: "string"
        example: "6 10 CCCGG ((((( YYYRR 262 266 CCGGG ))))) YYRRR"

    Residue:
      type: "object"
      properties:
        chainIdentifier:
          type: "string"
          example: "A"
        residueNumber:
          type: "integer"
          example: "16"
        insertionCode:
          type: "string"
          description: "null in some adapters"
        oneLetterName:
          type: "string"
          example: "G"
      required:
        - "chainIdentifier"
        - "residueNumber"
        - "oneLetterName"

    LeontisWesthof:
      type: "string"
      enum:
        - "cWW"
        - "cWH"
        - "cWS"
        - "cHW"
        - "cHH"
        - "cHS"
        - "cSW"
        - "cSH"
        - "cSS"
        - "tWW"
        - "tWH"
        - "tWS"
        - "tHW"
        - "tHH"
        - "tHS"
        - "tSW"
        - "tSH"
        - "tSS"

    Saenger:
      type: "string"
      enum:
        - "I"
        - "II"
        - "III"
        - "IV"
        - "V"
        - "VI"
        - "VII"
        - "VIII"
        - "IX"
        - "X"
        - "XI"
        - "XII"
        - "XIII"
        - "XIV"
        - "XV"
        - "XVI"
        - "XVII"
        - "XVIII"
        - "XIX"
        - "XX"
        - "XXI"
        - "XXII"
        - "XXIII"
        - "XXIV"
        - "XXV"
        - "XXVI"
        - "XXVII"
        - "XXVIII"

    BR:
      type: integer
      enum:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9

    BPh:
      type: integer
      enum:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9

    StackingTopology:
      type: string
      enum:
        - upward
        - downward
        - inward
        - outward

    VisualizationTool:
      type: "string"
      enum: [ "VARNA", "PSEUDO_VIEWER", "R_CHIE", "RNA_PUZZLER", "NONE" ]

    DrawingResult:
      type: "string"
      enum: [ "DONE_BY_MAIN_DRAWER", "DONE_BY_BACKUP_DRAWER", "FAILED_BY_BOTH_DRAWERS", "NOT_DRAWN" ]

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
